### ISSUE TITLE
Netznotfallzug

### ISSUE THREAD

**Issue by ChillLP** [marhei/TrainCompany-Data#14]
With that, New Type of Direktvergaben will be added and New Type of Cargo "Medicine"

**Comment by ChillLP** [comment]
And yes, this is a self assign once again.

**Comment by ChillLP** [comment]
Locowise might add V100

**Comment by ChillLP** [comment]
Will Probably use V60, just for the joke

**Comment by ChillLP** [comment]
@marhei Implement ability for trains to be able to do specific things if coupled in specific formation? (e.g. if V60+ Rtzg can go KRM and VDE 8)

**Comment by ChillLP** [comment]
Will be continued once above said is in the stages of being made

**Comment by marhei** [comment]
Ich werde mich da demnächst mal drum kümmern…
