### ISSUE TITLE
Siegstrecke hat Teilstück mit Länge 0

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#141]
Zwischen `EBRB` und `EMUD`

**Comment by C1710** [comment]
Es gibt noch mehrere...
Ich passe nachher mal das Schema an, dass sowas erkannt wird

**Comment by marhei** [comment]
Ah, ich werde das auch gleich mal intern Validieren, danke für den Hinweis.

**Comment by marhei** [comment]
Mit 386310b gefixt
