### ISSUE TITLE
AMUE without Path

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#156]
Müssen ist zwar bei den Stationen (und deshalb auch in der Task des RE von Hamburg nach Rostock), aber an keine Strecke angebunden.

**Comment by marhei** [comment]
Ah, das erklärt wieso der Bahnhof schon ein paar mal Exceptions geworfen hat…

**Comment by marhei** [comment]
Wenn man ein Ril100 löscht, dann sollte man es auch aus bereits generierten Ausschreibungen entfernen…
