### ISSUE TITLE
Fix Iserlohn-Letmahte

### ISSUE THREAD

**Issue by f2k1de** [marhei/TrainCompany-Data#184]
Ist nur auf einer Strecke verbunden.

**Comment by marhei** [comment]
Was meinst du damit?

**Comment by f2k1de** [comment]
![Bildschirmfoto 2022-07-03 um 15 16 01](https://user-images.githubusercontent.com/11199213/177046095-e0af8153-e6f6-4842-9525-77c9bbd12427.png)

**Comment by marhei** [comment]
Iserlohn liegt auch eigentlich gar nicht auf der anderen Strecke, ich hab den Bf etwas nach unten verschoben, damit das deutlicher wird.

**Comment by marhei** [comment]
Fix durch c333964
