### ISSUE TITLE
DE/AT-Zulassung für Twindexx Express?

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#228]
In diesem Bericht steht (S. 14), dass der Twindexx Express langfristig auch in Deutschland und Österreich zugelassen werden soll.
Soll ich das dann auch hier übernehmen oder eher rauslassen, weil die Zulassung noch nicht erfolgt ist und bei dem Teil irgendwie nicht sonderlich wahrscheinlich erscheint? 😂
https://company.sbb.ch/content/dam/internet/corporate/de/medien/dossier-medienschaffende/faktenblatt-fv-dosto/statusbericht-fv-dosto.pdf.sbbdownload.pdf

**Comment by marhei** [comment]
Ich würde den erstmal lassen. Vielleicht wäre es aber auch sinnvoll mal reinnationale CH-Leistungen anzubieten.
