### ISSUE TITLE
Ausschluss für Diesel-Fahrzeuge ermöglichen

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#230]
Mittelfristig wird denke ich auch der Gotthard-Basistunnel kommen und ich denke nicht (weiß es aber auch nicht sicher), dass da Diesel-Züge durch dürfen.
Natürlich ließe sich das auch mit einem `equipment` lösen (was vielleicht ohnehin nötig wird?), aber das müsste dann jedem E-Zug hinzugefügt werden.

**Comment by marhei** [comment]
Also Diesel-Züge von Strecken explizit ausschließlich? Ich schau mal…

**Comment by C1710** [comment]
Ich kann mir halt irgendwie nicht vorstellen, wie eine V60 durch den Gotthard-Basistunnel brettert 🥴

**Comment by C1710** [comment]
> Die Tc-Community wird dir das schon noch demonstrieren.

Ich meinte das jetzt eher realistisch. Über die KRM würde die doch in echt wohl eher auch nicht fahren 🥴

**Comment by embix** [comment]
> Ich kann mir halt irgendwie nicht vorstellen, wie eine V60 durch den Gotthard-Basistunnel brettert

Direkvergabe: Testfahrt/Kontroll/Messfahrt mit einem Bahndienstfahrzeug und einer Arbeitsrotte durch den $TUNNEL

Ist jetzt nicht der "Normalfall" aber sowas in der Art dürfte schon ab und an mal vorkommen. Oder rennen die Streckenläufer den ganzen Weg zu Fuß durch den Tunnel?

**Comment by marhei** [comment]
Wird nicht umgesetzt…
