### ISSUE TITLE
Change Name of Traverso

### ISSUE THREAD

**Issue by ChillLP** [marhei/TrainCompany-Data#240]
**Stadler Traverso** Traverso

to:

**Stadler Flirt 4** Traverso

![image](https://user-images.githubusercontent.com/105374102/178114679-bf7f1197-e573-4064-a1cf-02dc34ed13ea.png)
 @C1710

**Comment by C1710** [comment]
Traverso is technically still a Flirt 3 AFAIK

**Comment by ChillLP** [comment]
Nope, traverso is Flirt 4
https://de.wikipedia.org/wiki/Stadler_Flirt

**Comment by ChillLP** [comment]
Nevermind im Wrong
