### ISSUE TITLE
Wasserstoff als Antriebstyp

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#243]
Vergleichbar mit Batterie/Hybrid, nur, dass die Reichweite auch unter OL eine Rolle spielt.
Symbol könnte z.B. 💧 oder 💦 sein.  🫧 wäre auch möglich, ist aber leider noch nicht überall unterstützt (z.B. unter Windows 10, was bei der Emoji-Schriftart vermutlich gar keine Updates mehr bekommen wird)

**Comment by marhei** [comment]
Ich kümmere mich morgen drum.

**Comment by marhei** [comment]
So, ist implementiert, bitte auch Range für jedes Fahrzeug hinzufügen
