### ISSUE TITLE
Logik für neededEquipments

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#258]
Insbesondere bei den Zügen mit `neededEquipment` gibt es inzwischen leichte Probleme.  
So können die Eurostars hier nur in Frankreich fahren, wodurch ich Belgien und die HS1 auch als "Frankreich" einstufen musste, dass die da fahren können.

Eine Option, sowas ordentlich abbilden zu können, wäre, wenn `neededEquipments` per UND/ODER/NICHT konstruiert werden könnten.

Es ließe sich im JSON umsetzen als konjunktive Normalform (Also ein großes UND über die Equipments, wobei statt eines Equipments auch ein ODER über mehrere Equipments stehen kann; jedes Equipment kann auch negiert werden) - Bezeichnung übernommen von der JSON-Schema-Spezifikation:
```json
"neededEquipments": [
    "equipment",
    {
         "anyOf": [
             "equipment",
             "equipment",
            { "not": "equipment" },
            ...
        ]
    },
    "equipment",
    ...
]
```

**Comment by marhei** [comment]
Ja, das Problem ist mir auch gerade aufgefallen…

**Comment by marhei** [comment]
Ist entsprechend umgesetzt…
