### ISSUE TITLE
Norderweiterung

### ISSUE THREAD

**Issue by wiwospielt** [marhei/TrainCompany-Data#28]
Strecke von EHM nach HH über ERDW-EGLO-EBIL-HL-HWUN

**Comment by C1710** [comment]
Dazu dann noch Hannover — Celle — Uelzen — Lüneburg (?) — Hamburg und vielleicht noch was ab Münster?

**Comment by C1710** [comment]
WIP: Stationserweiterung nach Hamburg und Bremen

**Comment by marhei** [comment]
@C1710 goes BRRRRRRRRRRR!!!! Danke für deine ganze Arbeit!

**Comment by C1710** [comment]
> @C1710 goes BRRRRRRRRRRR!!!! Danke für deine ganze Arbeit!

Ich hab da eigentlich inzwischen ein recht gutes System, um die Strecken hinzuzufügen:
1. Erst gucke ich auf Openrailwaymap, was für Bahnhöfe/Strecken dazukommen sollen
2. Dann füge ich Punkte mit Namen auf meiner Karte ein (die habe ich so skaliert, dass ein Pixel einem Punkt im Koordinatensystem entspricht)
3. Dann gehe ich den Trassenfinder nach den RIL100-Codes durch und benenne die Punkte im Grafikprogramm entsprechend
4. Dann suche ich auf https://www.deutschebahn.com/de/geschaefte/infrastruktur/bahnhof/bahnsteige_uebersicht/? die Bahnsteiglängen und -Anzahl raus und füge die ebenfalls hinzu
5. Der Trassenfinder liefert die Abschnittslängen
Openrailwaymap die Höchstgeschwindigkeiten und Kurvigkeit, damit werden die Linien dann benannt
6. Dann kommt das alles in die JSONs. Weil ich bei den Koordinaten nicht rumrechnen will, verschiebe ich die vorher per Script, sodass die Koordinaten im Bild denen auf der Karte entsprechen. Die Daten kann ich einfach eben abtippen und dann am Ende das Koordinatensystem wieder zurückschieben :D

Im Prinzip ist es einfach nur viel Aptippen 😂
Aber irgendwie gut geeignet zum Masterarbeits-Proposal prokrastinieren 🥴

**Comment by marhei** [comment]
Als nächstes dann wohl am besten Ruhrgebiet-Bremen, um die Lücke oben links zu schließen.

**Comment by C1710** [comment]
Ich denke, als nächstes werde ich den Rest Nordwest-Niedersachsens (und Bremen) versuchen, abzudecken bis Norddeich-Mole, Emden und Wilhelmshaven, Oldenburg, Bremerhaven.

**Comment by marhei** [comment]
@f2k1de Als nächstes vielleicht auch Hamburg-Lübeck. Und bitte mehr Unterwegsbahnhöfe pro Strecke!
