### ISSUE TITLE
Westerweiterung

### ISSUE THREAD

**Issue by ChillLP** [marhei/TrainCompany-Data#30]

**Comment by ChillLP** [comment]
Eventuell KG, aber richung KA und auch weiter richung grenze BE/NL

**Comment by ChillLP** [comment]
Wird definitiv richtung XN und XB gehen noch.

**Comment by ChillLP** [comment]
oOOAAARGHHH

**Comment by f2k1de** [comment]
Wo Belgien? Wo Emmerich?

**Comment by ChillLP** [comment]
Junger mann is keine Drehstromlok
