### ISSUE TITLE
Bordeaux-Toulouse-Narbonne

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#364]
- Vielleicht auch mit der geplanten LGV?
- Dann Airbus-Aufträge zwischen Toulouse und Hamburg?

**Comment by marhei** [comment]
> * Vielleicht auch mit der geplanten LGV?
Gerne als Ergänzung
> * Dann Airbus-Aufträge zwischen Toulouse und Hamburg?
Klingt gut!
