### ISSUE TITLE
Class 92

### ISSUE THREAD

**Issue by Emuricdo** [marhei/TrainCompany-Data#366]
Könnte für Güterzüge durch den Eurotunnel eingesetzt werden.

Der Code dafür könnte so aussehen:

	
```
                        "group": 0,
			"name": "Class 92",
			"speed": 140,
			"weight": 126,
			"force": 360,
			"length": 21,
			"drive": 1,
			"reliability": 0,85,
			"cost": 380000,
			"operationCosts": 110,
			"equipments": ["FR", "GB", "TVM", "Eurotunnel" ]

```

**Comment by C1710** [comment]
Die Class 92 hat meines Wissens nach keine FR-Zulassung, weshalb das auch erst jetzt mit dem Lokwechsel funktioniert 😅

**Comment by Emuricdo** [comment]
Ich dachte ehrlich gesagt, dass die sie hätte. Allerdings würde es ohne Frankreich-Zulassung hier dann nur wenig Sinn ergeben, da man die derzeit für den Eurotunnel benötigt.

**Comment by C1710** [comment]
> Ich dachte ehrlich gesagt, dass die sie hätte. Allerdings würde es ohne Frankreich-Zulassung hier dann nur wenig Sinn ergeben, da man die derzeit für den Eurotunnel benötigt.

Die Länderzulassung ließe sich vielleicht rausnehmen, da für den €-Tunnel eh schon eine separate Zulassung gebraucht wird.

@marhei würde das Sinn ergeben?

**Comment by marhei** [comment]
Also, Strecke ohne Länderzulassung funktioniert nicht, der Tunnel würde dadurch automatisch zu Deutschland werden.

**Comment by C1710** [comment]
> Also, Strecke ohne Länderzulassung funktioniert nicht, der Tunnel würde dadurch automatisch zu Deutschland werden.

Das funktioniert auch nicht, wenn die Eurotunnel-Zulassung vorhanden ist?

Könnte es ansonsten als (nur) UK eingestuft werden? Es gibt doch ansonsten keine Züge, die Frankreich + Eurotunnel, aber nicht UK können, oder?

**Comment by marhei** [comment]
Ja, nur UK wäre möglich. Eurotunnel selbst in kein Country-Equipment und würde deswegen immer um das default-Land ergänzt werden.
