### ISSUE TITLE
Nightjet

### ISSUE THREAD

**Issue by ChillLP** [marhei/TrainCompany-Data#38]
Is it possible to have direktvergaben that only are avalible at specific times of day? (@marhei)

Cargo: Beds
Needs specific WLABmz/ Nightjet wagons
Pullable by every loco

**Comment by marhei** [comment]
Nicht möglich derzeit…

**Comment by ChillLP** [comment]
Diesem und dem Notfallzug ein label "ToBe Integrated" odre so verpassen?
