### ISSUE TITLE
ICNG

### ISSUE THREAD

**Issue by Emuricdo** [marhei/TrainCompany-Data#382]
Ich hatte letzte Woche auf Twitter den ICNG in der für Belgien tauglichen Version für die IC-Direct-Ausschreibungen vorgeschlagen und würde hiermit die Daten, die ich soweit dazu herausgefunden habe, dafür bereitstellen. Ich bin mir allerdings nicht sicher, ob alles wirklich richtig ist, da die Datenlage dazu dürftiger ist, als ich erwartet hatte. 
```

			"id": 3300,
			"group": 2,
			"name": "Intercity Nieuwe Generatie",
			"shortcut": "ICNG",
			"speed": 200,
			"weight": 332,
			"force": 584,
			"length": 165,
			"drive": 1,
			"reliability": 1,
			"cost": 750000,
			"operationCosts": 100,
			"maxConnectedUnits": 2,
			"equipments": ["NL", "BE", "ETCS" ],
			"exchangeTime": 60,
			"capacity": [
				{"name": "passengers", "value": 410}
```

**Comment by C1710** [comment]
Die Datenlage zu neuen Zügen ist meistens eher schlecht 😅

**Comment by C1710** [comment]
Die Anfahrzugkraft erscheint mir aber etwas sehr hoch 🤔

**Comment by Emuricdo** [comment]
Das würde ehrlich gesagt mehr Sinn ergeben als den Wert, den ich herausgefunden habe.
