### ISSUE TITLE
Paris-Lille-Calais (Altbau)

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#386]
Damit auch ein lokbespannter Verkehr zum Eurotunnel möglich ist

**Comment by marhei** [comment]
Vielleicht auch die Strecke über Armiens und Bologne sur mer… :)

**Comment by C1710** [comment]
> Vielleicht auch die Strecke über Armiens und Bologne sur mer… :)

Wäre vielleicht ganz gut um mehr neue Städte zu erschließen 🤔

**Comment by C1710** [comment]
Schon mal als Warnung: Der Abzweig `FR:VEMARS` (südliches Ende LGV Nord) wird gestrichen, bzw. ersetzt durch den in der nähe gelegenen Hp Survilliers Fosses.

Oder soll ich das bisherige Kürzel weiter verwenden und die restlichen Daten vom Haltepunkt übernehmen?

**Comment by marhei** [comment]
Du kannst den gerne umbenennen, ich kümmere mich dann darum.

**Comment by C1710** [comment]
Uuund es hat's kapuut gemacht 😬

**Comment by marhei** [comment]
Ja, es gab eine Strecke doppelt. Die Zugfahrten, die kaputt gegangen sind wurden jetzt von mir händisch gefixt.
