### ISSUE TITLE
KISS 160 mit ETCS?

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#392]
Also bei der S-Bahn Zürich (worauf der KISS hier ja ursprünglich basiert) bin ich mir nicht sicher, ob die ETCS haben.
Aber bei den CFL-KISS, die ja auch teilweise als Vorlage dienen, ist lt. WIkipedia definitiv ETCS enthalten.

Soll das dann hier auch hinzugefügt werden?
(Ggf. zumindest zur nächsten Runde mit einer leichten Preiserhöhung)

**Comment by marhei** [comment]
Der CFL-Kiss hat bestimmt ETCS, da es in Luxemburg nur noch ETCS als Zugsicherungssystem gibt.
