### ISSUE TITLE
Twitter-Integration - Fehler bei Abfrage

### ISSUE THREAD

**Issue by PRollbis** [marhei/TrainCompany-Data#399]
Klickt man auf einen Twitter-Benutzernamen so erfolgt im Browser die Abfrage, ob die Twitter-Seite geöffnet werden soll. Ein Klick auf "Abbrechen" öffnet die Seite mit dem Profil dennoch.

Browser: Safari 15.5
System: macOS 12.4

**Comment by C1710** [comment]
Das ist wahrscheinlich ein Problem von Safari und nicht von der Website. Das ist schließlich einfach nur ein Link.

**Comment by marhei** [comment]
Ja, ich verlinke einfach nur das Twitter-Profil, es gibt von Seiten TrainCompany keine Abfrage ob die Seite geöffnet werden soll.
