### ISSUE TITLE
Orient-Express & Optima-Express

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#429]
## Art der Erweiterung
[x] Strecke
[x] Zug
[x] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Aufgaben:
- [x] Strecken
  - [x] Wien-Budapest
    - [x] Österr. Ostbahn
    - [x] Budapest–Hegyeshalom
  - [x] Budapest-Beograd
  - [x] Beograd-Sofia
  - [x] Sofia-Istanbul
  - [x] Venezia-Triest-Ljubljana
  - [x] Salzburg-Villach-Ljubljana-Zagreb-Beograd
    - [x] Salzburg-Villach
    - [x] Villach-Ljubljana
    - [x] Ljubljana-Zagreb
    - [x] Zagreb-Beograd
  - [ ] Ggf. Strecke(n) nach Griechenland
- [x] Kompatible Loks und Länder
  - [x] Slowenien
  - [x] Ungarn (da muss dann auch noch der Desiro ML zugelassen werden)
  - [x] Kroatien
  - [x] Serbien
  - [x] Bulgarien
  - [x] Türkei
  - [ ] Ggf. Nord-Mazedonien
  - [ ] Ggf. Griechenland
- [x] Tasks
  - [x] Orient-Express nach Istanbul
  - [x] Optima-Express
  - [x] Ggf. Teilstrecken
  - [x] Linie 18 von Köln(?) nach Istanbul

**Comment by C1710** [comment]
Wenn jemand Teile übernehmen möchte, bitte melden :D

**Comment by ChillLP** [comment]
Die 18 dann aber bitte Mit BOStrab Fahrzeugen Only, ja?

**Comment by ChillLP** [comment]
Da lässt sich bestimmt was einrichten

**Comment by Emuricdo** [comment]
> Wenn jemand Teile übernehmen möchte, bitte melden :D
> 
> (Vor allem bzgl. neuer Züge/Loks)

Wenn daran Interesse besteht, würde ich das Rollmaterial übernehmen wollen.

**Comment by C1710** [comment]
> > Wenn jemand Teile übernehmen möchte, bitte melden :D
> > (Vor allem bzgl. neuer Züge/Loks)
> 
> Wenn daran Interesse besteht, würde ich das Rollmaterial übernehmen wollen.

Kannst du gerne machen :D

**Comment by Emuricdo** [comment]
Ich habe mir dazu einige Gedanken gemacht und würde zumindest einige der folgenden Lokomotiven hinzufügen wollen:

Elektrolokomotiven:

441 (Bosnien, Kroatien, Serbien, Mazedonien, Türkei)
461 (Montenegro, Serbien, Mazedonien, Bulgarien)
342 (Slovenien, Italien)
363 (Slovenien)
541 (Slowenien, Österreich, Italien, Kroatien, Deutschland, Ungarn), könnte durch Hinzufügung fehlender Zulassungen der ES64U4 implementiert werden
1142 (Kroatien)
42.1 (Bulgarien)
1080 (Bulgarien)
120 (Griechenland)
E43000 (Türkei)
E68009 (Türkei)

Daneben würde ich vorschlagen, für die Relation die Vectron mit Zulassungen für Slowenien, Kroatien, Serbien, Bulgarien und der Türkei, für die Traxx F140 AC2 Zulassungen für Slowenien, Kroatien und Serbien und für die F140 AC3 eine Zulassung für Rumänien hinzuzufügen.

Diesellokomotiven:

661 (Bosnien, Kroatien, Slowenien, Serbien, Montenegro, Kosovo)
645 (Kroatien, Slowenien, Serbien)
666 (Serbien)
04 (Bulgarien)
220 (Griechenland)
A-450 (Griechenland)
DE22000 (Türkei) oder DE24000 (Türkei)

**Comment by marhei** [comment]
Ich habe BR 183 und 193 mal um entsprechende Zulassungen ergänzt.

**Comment by Emuricdo** [comment]
> 

Danke.

**Comment by marhei** [comment]
Da es derzeit keine Diesellok mit Serbienzulassung gibt sind Tasks östlich von Nis nicht durchführbar…

**Comment by Emuricdo** [comment]
> Da es derzeit keine Diesellok mit Serbienzulassung gibt sind Tasks östlich von Nis nicht durchführbar…

Ich werde am Abend dafür geeignete Lokomotiven fertigstellen.

**Comment by marhei** [comment]
> > Da es derzeit keine Diesellok mit Serbienzulassung gibt sind Tasks östlich von Nis nicht durchführbar…
> 
> 
> 
> Ich werde am Abend dafür geeignete Lokomotiven fertigstellen. 

Danke für eure Mühe! 🥰

**Comment by Emuricdo** [comment]
Ich hätte wegen den Teilstrecken eine Frage: Sind ausschließlich Fernverkehrsverbindungen vorgesehen oder sind auch Regionalverbindungen möglich?

**Comment by marhei** [comment]
> Ich hätte wegen den Teilstrecken eine Frage: Sind ausschließlich Fernverkehrsverbindungen vorgesehen oder sind auch Regionalverbindungen möglich?

Gerne auch Regionalverbindungen

**Comment by Emuricdo** [comment]
> > Ich hätte wegen den Teilstrecken eine Frage: Sind ausschließlich Fernverkehrsverbindungen vorgesehen oder sind auch Regionalverbindungen möglich?
> 
> Gerne auch Regionalverbindungen

Danke, ich hätte dazu nämlich schon einige Ideen.

**Comment by C1710** [comment]
> > > Ich hätte wegen den Teilstrecken eine Frage: Sind ausschließlich Fernverkehrsverbindungen vorgesehen oder sind auch Regionalverbindungen möglich?
> > 
> > 
> > Gerne auch Regionalverbindungen
> 
> Danke, ich hätte dazu nämlich schon einige Ideen.

Machst du auch schon die Fernverkehrs-Ausschreibungen/Direktvergaben oder möchtest du nur Regional machen?

**Comment by Emuricdo** [comment]
> > > > Ich hätte wegen den Teilstrecken eine Frage: Sind ausschließlich Fernverkehrsverbindungen vorgesehen oder sind auch Regionalverbindungen möglich?
> > > 
> > > 
> > > Gerne auch Regionalverbindungen
> > 
> > 
> > Danke, ich hätte dazu nämlich schon einige Ideen.
> 
> Machst du auch schon die Fernverkehrs-Ausschreibungen/Direktvergaben oder möchtest du nur Regional machen?

Wenn es dich nichts ausmachen würde, würde ich auch die Fernverkehrsausschreibungen übernehmen wollen.

**Comment by C1710** [comment]
> > > > > Ich hätte wegen den Teilstrecken eine Frage: Sind ausschließlich Fernverkehrsverbindungen vorgesehen oder sind auch Regionalverbindungen möglich?
> > > > 
> > > > 
> > > > Gerne auch Regionalverbindungen
> > > 
> > > 
> > > Danke, ich hätte dazu nämlich schon einige Ideen.
> > 
> > Machst du auch schon die Fernverkehrs-Ausschreibungen/Direktvergaben oder möchtest du nur Regional machen?
> 
> Wenn es dich nichts ausmachen würde, würde ich auch die Fernverkehrsausschreibungen übernehmen wollen.

Ausschreibungen erstellen finde ich eher langweilig, von daher kannst du das sehr gerne machen 😂

**Comment by Emuricdo** [comment]
> > > > > > Ich hätte wegen den Teilstrecken eine Frage: Sind ausschließlich Fernverkehrsverbindungen vorgesehen oder sind auch Regionalverbindungen möglich?
> > > > > 
> > > > > 
> > > > > Gerne auch Regionalverbindungen
> > > > 
> > > > 
> > > > Danke, ich hätte dazu nämlich schon einige Ideen.
> > > 
> > > 
> > > Machst du auch schon die Fernverkehrs-Ausschreibungen/Direktvergaben oder möchtest du nur Regional machen?
> > 
> > 
> > Wenn es dich nichts ausmachen würde, würde ich auch die Fernverkehrsausschreibungen übernehmen wollen.
> 
> Ausschreibungen erstellen finde ich eher langweilig, von daher kannst du das sehr gerne machen 😂

OK, ich fange dann mit der Erstellung an.

**Comment by C1710** [comment]
> Die 18 dann aber bitte Mit BOStrab Fahrzeugen Only, ja?

Achso, gibt es eigentlich einen Tram-Train, der auch Länderzulassungen Österreich, Ungarn (oder Italien, Slowenien, Kroatien), Serbien, Bulgarien, Türkei hat und auch auf nicht-elektrifizierten Strecken fahren kann?

**Comment by marhei** [comment]
> > Die 18 dann aber bitte Mit BOStrab Fahrzeugen Only, ja?
> 
> 
> 
> Achso, gibt es eigentlich einen Tram-Train, der auch Länderzulassungen Österreich, Ungarn (oder Italien, Slowenien, Kroatien), Serbien, Bulgarien, Türkei hat und auch auf nicht-elektrifizierten Strecken fahren kann?


Nein, das ist nicht möglich ohne sich irgendein Fahrzeug aus den Fingern zu ziehen. Gerne als Task ohne BOStrab

**Comment by C1710** [comment]
> > > Die 18 dann aber bitte Mit BOStrab Fahrzeugen Only, ja?
> > 
> > 
> > Achso, gibt es eigentlich einen Tram-Train, der auch Länderzulassungen Österreich, Ungarn (oder Italien, Slowenien, Kroatien), Serbien, Bulgarien, Türkei hat und auch auf nicht-elektrifizierten Strecken fahren kann?
> 
> Nein, das ist nicht möglich ohne sich irgendein Fahrzeug aus den Fingern zu ziehen. Gerne als Task ohne BOStrab

Das macht aber irgendwie den Witz kaputt :D

Dann vielleicht als einfacher Direktzug Köln-Istanbul?

**Comment by C1710** [comment]
Ich sehe gerade, der VSOE Paris-Istanbul fährt über Rumänien, was noch nicht geht. Ich streiche den dann hier erstmal und das kommt dann separat.
