### ISSUE TITLE
feat(extension): Add Transsibirische Eisenbahn

### ISSUE THREAD

**Issue by weiland** [marhei/TrainCompany-Data#445]
## Was wird hinzugefügt? 👀

__Transsib__

Die Transsibirische Eisenbahn. 🚂 
https://de.wikipedia.org/wiki/Transsibirische_Eisenbahn 

## Art der Erweiterung ⚒️

[x] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details 📝

- ist sehr cool
- und lang
- Marcel wird damit sehr viel Spaß haben 👀

**Comment by C1710** [comment]
Dazu bräuchte es erstmal eine Datenquelle für irgendwelche Bahnhofs-Codes 😵‍💫

Wladiwostok z.B. hat kein RIL100 und auch in den Datensätzen von trainline.eu gibt es keinen UIC-Code dafür 🥴

**Comment by C1710** [comment]
Und es bräuchte wahrscheinlich dann auch eine richtige Globusansicht 😂

**Comment by marhei** [comment]
> Und es bräuchte wahrscheinlich dann auch eine richtige Globusansicht 😂

Das ist doch der einzige Grund wieso er es vorgeschlagen hat: Um TC kaputt zu machen. 🥲
