### ISSUE TITLE
Idea: Backggrpimd

### ISSUE THREAD

**Issue by ChillLP** [marhei/TrainCompany-Data#450]
Change the Background to a newwer version of the map with a projection (live) od current vehicles running there? (Ingame or IRL)

**Comment by marhei** [comment]
Die Karte im Hintergrund war nie eine Abbildung der Spielkarte. Auf allen Seiten im Hintergrund die echten Züge fahren lassen würde enorm viel Ressourcen kosten.

**Comment by ChillLP** [comment]
Fair enough
