### ISSUE TITLE
Hochgeschwindigkeitsnetz Spanien

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#490]
## Was wird hinzugefügt?
Die restlichen HGV-Strecken in Spanien: https://de.wikipedia.org/wiki/Schnellfahrstrecke#Strecken%C3%BCbersicht_4
## Art der Erweiterung
[x] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Wahrscheinlich kommen zunächst die Strecken >= 300 km/h oder so

**Comment by C1710** [comment]
Todo:
- [ ] https://de.wikipedia.org/wiki/Schnellfahrstrecke_Madrid%E2%80%93Levante
- [ ] https://de.wikipedia.org/wiki/Schnellfahrstrecke_Madrid%E2%80%93Valladolid
- [ ] https://de.wikipedia.org/wiki/Schnellfahrstrecke_Madrid%E2%80%93Sevilla
- [ ] https://de.wikipedia.org/wiki/Schnellfahrstrecke_C%C3%B3rdoba%E2%80%93M%C3%A1laga
- [ ] https://en.wikipedia.org/wiki/Madrid%E2%80%93Galicia_high-speed_rail_line

**Comment by Emuricdo** [comment]
Werden eigentlich noch Aufträge für die Strecken benötigt? Ansonsten hätte ich etwas vorbereitet.

**Comment by C1710** [comment]
> Werden eigentlich noch Aufträge für die Strecken benötigt? Ansonsten hätte ich etwas vorbereitet.

Aufträge hab ich keine erstellt 😅
(Dafür bin ich meistens zu faul 😬)
