### ISSUE TITLE
Salon-Wagen für Luxuszüge

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#497]
## Was wird hinzugefügt?
Ein oder mehrere Salonwagen für Luxuszüge (damit nicht irgendein Nightjet plötzlich den Venice Simplon Orient Express fährt).
## Art der Erweiterung
[ ] Strecke
[x] Zug
[ ] Aufgabe
[x] Ladungsart
[ ] Verspätung

## Weitere Details
Ließe sich analog zu den `bistroseats` lösen.

**Comment by embix** [comment]
Oh cool, dann kann der VT 10 551 Komet aus #389  

- a) um den [Salonwagen VT 10 551i](https://de.wikipedia.org/wiki/DB_VT_10_551i) ergänzt werden (bzw. ein "normaler" Sitzwagen / die Plätze müssen abgezogen werden - wegen mangelnder Motorleistung ist nur Tausch vorgesehen)
- b) oder wir behalten den Komet so wie er ist und der um den Salonwagen ergänzte/getauschte VT 10 551i wird als eigenes Triebfahrzeug eingeführt.

**Comment by embix** [comment]
Und wenn dir diese Züge nicht für den Orient-Express passen sollten, kannst du ja immer noch den Salonbedarf bei den Orient-Express Jobs auf einen höheren Wert setzen, als der bei den beiden VTs eingestellt ist/wird. 😉
