### ISSUE TITLE
Bruxelles-Namur-Luxenbourg

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#499]
## Art der Erweiterung
[x] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Für einen Orient-Express relevant, sowie allgemein Züge von Belgien nach Südosten

**Comment by embix** [comment]
wird auch gebraucht für TEE Iris #389
