### ISSUE TITLE
Ostende-Brügge-Gent

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#500]
## Was wird hinzugefügt?
Kleine Streckenerweiterung nach Ostende, damit z.B. die zwei Orient-Express-Kurswagen durchfahren können
## Art der Erweiterung
[x] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

**Comment by embix** [comment]
👍 Ostende brauch ich auch für den TEE Saphir
