### ISSUE TITLE
Bordeaux-Hendaye-Burgos

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#534]
## Was wird hinzugefügt?
Eine zweite grenzüberschreitende Strecke zwischen Frankreich und Spanien
## Art der Erweiterung
[x] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Problem: Breitspur(?)

**Comment by marhei** [comment]
Ich kümmere mich morgen mal um das Thema Spurweiten…

**Comment by C1710** [comment]
> Ich kümmere mich morgen mal um das Thema Spurweiten…

Kein Stress 😄
Gibt ja auch noch genug andere Strecken 👀
