### ISSUE TITLE
Task 115749 TER Le Mans–Vitré muss über die LGV

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#538]
Vermutlich ist da die Reihenfolge durcheinander.

**Comment by Emuricdo** [comment]
Das ist seltsam. Ich dachte, dass ich es so eingestellt hätte, dass es über Sillé-le-Guillaume auf der Altbaustrecke führen würde. Ich habe dafür eine pathSuggestion über eine Altbaustrecke hinzugefügt, die das Problem hoffentlich beheben wird.

**Comment by C1710** [comment]
> Das ist seltsam. Ich dachte, dass ich es so eingestellt hätte, dass es über Sillé-le-Guillaume auf der Altbaustrecke führen würde. Ich habe dafür eine pathSuggestion über eine Altbaustrecke hinzugefügt, die das Problem hoffentlich beheben wird.

Das Problem liegt glaube ich daran, dass zwei Haltestellen in der falschen Reihenfolge sind 😅

**Comment by Emuricdo** [comment]
Ich sehe es mir nochmal an.

**Comment by Emuricdo** [comment]
Ich habe es mir nochmal angesehen und bei mir wird der Weg auf der Altbaustrecke angezeigt.
Ich habe die Reihenfolge XFLM-🇫🇷SLG-XFLAL-XFVTE-XFR verwendet.

**Comment by C1710** [comment]
Hm, komisch. Es war aber irgendwie so, dass ich XFVTE-XFR-XFLAL (oder so) musste. Ich habe aber glaub ich leider vergessen, einen Screenshot zu machen...
