### ISSUE TITLE
Sud-Express

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#577]
## Was wird hinzugefügt?
https://de.wikipedia.org/wiki/Sud-Express
## Art der Erweiterung
[ ] Strecke
[ ] Zug
[x] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Benötigt:
- [x] #534
- [x] #576 
- [x] Passende Züge für iberische Breitspur und Portugal - Keine Ahnung, ob schon vorhanden

**Comment by marhei** [comment]
60fe3ec4ba8813e288277a3fafde945efe1d8b87
