### ISSUE TITLE
Größere Karte

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#645]
Weil die Transsibirische Eisenbahn und bald die LGV in Marokko außerhalb der aktuellen Karte liegen, braucht es eine Erweiterung.

Dabei würde ich vorschlagen, direkt eine Weltkarte zu nehmen.
Ich habe dazu auch schon eine rausgesucht, die zumindest noch eine halbwegs akzeptable Qualität hat.

Aber: Die verwendet CSS. 
Das Gute: Darkmode kann explizit eingestellt werden.
Das Schlechte: Die Karte kann so nicht mehr als `image` in die Netz-SVG gestopft werden, sondern müsste direkt im HTML (etwa per `img`) eingebunden werden. Allerdings weiß ich nicht, wie das mit dem Verschieben usw. geht (dafür wird es allerdings sicherlich irgendwelche Lösungen geben).

**Comment by C1710** [comment]
@marhei Wie sollte die Karte am besten gestaltet sein?
Ich habe die jetzt so eingestellt, dass der 0-Punkt am 0-Punkt des Korrdinatensystems für das Netz ist und 1 Pixel einem Koordinatenpunkt entspricht.

**Comment by marhei** [comment]
<img width="952" alt="Capture d’écran 2022-08-22 à 12 29 31" src="https://user-images.githubusercontent.com/10304183/185900434-f7a8a1e3-670e-4d59-9ac9-9dbc67351178.png">
Also ich habe die Karte mal so wie du das anvisiert hattest eingebunden. Ganz perfekt passt es leider nicht…

**Comment by C1710** [comment]
> <img width="952" alt="Capture d’écran 2022-08-22 à 12 29 31" src="https://user-images.githubusercontent.com/10304183/185900434-f7a8a1e3-670e-4d59-9ac9-9dbc67351178.png">
> Also ich habe die Karte mal so wie du das anvisiert hattest eingebunden. Ganz perfekt passt es leider nicht…

Vielleicht mal in der SVG den Skalierungs-Faktor in y-Richtung noch etwas erhöhen oder so?

Heute schaffe ich es vsl. nicht mehr, noch was dran zu machen

**Comment by marhei** [comment]
Ich probiere da gleich nochmal etwas rum, muss auch noch ein paar andere Dinge machen bevor das heute Abend neustarten… 😵‍💫

**Comment by C1710** [comment]
> Ich probiere da gleich nochmal etwas rum, muss auch noch ein paar andere Dinge machen bevor das heute Abend neustarten… 😵‍💫

Im Zweifelsfall musst du den Neustart um einen Tag verschieben. Finden ja einige eh blöd :D
