### ISSUE TITLE
Anbindung von Sizilien 

### ISSUE THREAD

**Issue by marhei** [marhei/TrainCompany-Data#667]
## Art der Erweiterung
[X ] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Fähre zwischen Villa San Giovanni und Messina

**Comment by C1710** [comment]
Soll die Fähre als normale Strecke laufen oder einen eigenen Typ bekommen? (Dann z.B. mit gestrichelter Linie)

**Comment by marhei** [comment]
Schau mal in der Readme was da zum Thema Fähre steht… 👀

**Comment by C1710** [comment]
Soll die Fähre "elektrifiziert" sein?

**Comment by marhei** [comment]
Denke, dass wäre so erstmal am einfachsten…
