### ISSUE TITLE
USA-Erweiterungen

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#687]
## Was wird hinzugefügt?
Strecken in den USA
## Art der Erweiterung
[x] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Vorschläge sind willkommen!

**Comment by Emuricdo** [comment]
Wie wäre es mit dem Empire Corridor zwischen New York und Buffalo? Ab dort könnte man Strecken nach Chicago und Toronto einrichten.

**Comment by C1710** [comment]
> Wie wäre es mit dem Empire Corridor zwischen New York und Buffalo? Ab dort könnte man Strecken nach Chicago und Toronto einrichten.

Das ist bereits geplant 😄

**Comment by C1710** [comment]
@marhei Ist es okay, wenn die Stations-Abstände da länger (also teils so ~120 km o.Ä.) sind? In den USA haben sie's wohl eher nicht so mit Bahnhöfen/Haltepunkten 🤔
