### ISSUE TITLE
Amtrak Wagenmaterial

### ISSUE THREAD

**Issue by C1710** [marhei/TrainCompany-Data#691]
## Was wird hinzugefügt?
Verschiedene Loks und Wagen für die USA

## Art der Erweiterung
[ ] Strecke
[x] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
- [ ] Superliner*
- [ ] VIewliner
- [x] GE Genesis P42DC

*Wird in Europa unrealistisch, weil zu groß

**Comment by Emuricdo** [comment]
Würde es etwas ausmachen, wenn ich die Wagen erstellen würde?

**Comment by C1710** [comment]
> Würde es etwas ausmachen, wenn ich die Wagen erstellen würde? 

Absolut nicht 👀

**Comment by Emuricdo** [comment]
OK, dann fange ich mit der Arbeit an.
