### ISSUE TITLE
Test schlagen fehl bei null für eine zufällige Station

### ISSUE THREAD

**Issue by marhei** [marhei/TrainCompany-Data#694]
Gemäß https://github.com/marhei/TrainCompany/issues/157 wurde nun der Umgang mit zufälligen Stationen verbessert. Die Test kommen jedoch nicht mit null als Station zurecht und schlagen fehl.

**Comment by C1710** [comment]
Einen Moment. Ich mache nur noch eben schnell was fertig, dann probiere ich aus, ob meine Fixes reichen...
