### ISSUE TITLE
Ist eine Erweiterung um München-Pasing und München-Ost auf der Map machbar und sinnvoll?

### ISSUE THREAD

**Issue by MVGFan8xx** [marhei/TrainCompany-Data#703]
## Was wird hinzugefügt?
Also geplant sind München-Pasing und München-Ost.

## Art der (geplanten) Erweiterung
[x] Strecke
[ ] Zug
[ ] Aufgabe
[ ] Ladungsart
[ ] Verspätung

## Weitere Details
Also das letzte mal dass ich es versucht habe, wollte @marhei Pasing nicht. Da jetzt aber die Map sehr stark angewachsen ist, wollte ich nachfragen ob es mittlerweile nicht sinnvoll wäre MP und MOP hinzuzufügen

**Comment by marhei** [comment]
Ich halte es immer noch nicht für Großstädte mehr als einen großen Bf zu haben.

**Comment by MVGFan8xx** [comment]
oki dann hats sich erledigt
