### ISSUE TITLE
PathSuggestion-Test schlägt fehl

### ISSUE THREAD

**Issue by marhei** [marhei/TrainCompany-Data#713]
Ohne wirklich Grund ist der PathSuggestion-Test bei d3d66c10aba42ec3dc0fb399ac3a028602b052c8 fehlgehschlagen.

**Comment by C1710** [comment]
Das liegt ganz einfach daran, dass es keine Zugkategorie 5 gibt 😅

**Comment by marhei** [comment]
Doch gibt es, ist auch im Schema ergänzt worden.

**Comment by marhei** [comment]
Ich danke dir! :)

**Comment by C1710** [comment]
> Doch gibt es, ist auch im Schema ergänzt worden.

Aber wenn du sowas neu hinzufügst, ist es klar, dass das Probleme geben wird :D
