### ISSUE TITLE
Fehlender Bahnhof "Kiel-Hassee" auf Strecke Kiel-Eckernförde bzw. Kiel-Rendsburg

### ISSUE THREAD

**Issue by 99thGamer9** [marhei/TrainCompany-Data#766]
Hallo,
Auf den Strecken Kiel-Eckernförde und Kiel-Rendsburg fehlt der Bahnhof Hassee, auch wenn deutlich kleinere Haltepunkte wie Kronshagen und Russee vorhanden sind. Deshalb wollte ich fragen, ob das einen technischen Hintergrund hat bzw. absichtlich so gemacht wurde, oder ob dieser nur vergessen wurde.

**Comment by marhei** [comment]
Die Idee dahinter war es, die Verzweigung der beiden Strecken nach Kiel Hbf zunehmen und dadurch die Karte zu vereinfachen.
