### ISSUE TITLE
Automatic import of stations

### ISSUE THREAD

**Issue by bjoernma** [marhei/TrainCompany-Data#91]
It's possible to automatically generate a json with x / y / name / ril100 / group (categorization can be done due railway=halt (group=2), railway=service_station (group=3), railway=yard (group=3), railway=junction (group=4) and railway=station (group=0 or 1) from OSM data. (have tested it successfully for Niedersachsen in python, can provide the code...)

What do you think about it? There is some work yet to be done regarding the inclusion of the DB open data stuff for getting information about the platform length and number of them per station. But this information is available (ril100 links to "Übersicht Bahnhöfe" which links via Bahnhofsnummer to Bahnsteigdaten where each platform has a number and length. 

Some possible problems: not all osm data is complete (e.g. regarding name / ril100); some of the stations don't belong to railway but more of narrow gauge lines (Feldbahnen...). non-DB stations doesn't have platform information in the DB open data portal.

**Comment by C1710** [comment]
I already have a set of scripts that do this: https://github.com/C1710/TrainCompany-tools

There you can import a Trassenfinder.de-CSV export and it adds stations and routes (except max speed and twistingFactor).

Does OpenRailwayMap have an API or something that could be used to get maxSpeeds?

**Comment by C1710** [comment]
Your script may be useful for stations outside of Germany though 🤔

**Comment by bjoernma** [comment]
Maxspeeds are a bit more complicated as it's about many small line sections (and it's by actual track basis and not "one" big connection between stations) and the question of whether even small 20m sections of lower speed should be acknowledged. 
Basically it is possible using overpass-turbo.eu/ where you can get all ways with "railway=rail" and maxspeed in a Bundesland by using 
[out:json][timeout:250];
{{geocodeArea:Niedersachsen}}->.searchArea;
(  way["railway"="rail"][maxspeed](area.searchArea);
);
out body;
>;
out skel qt;

It has to be kept in mind that the data is not complete yet and may contain errors...

**Comment by marhei** [comment]
Um dem Problem mit den Höchstgeschwindigkeiten gerecht zu werden, gibt es den Twisting-Factor, der Teil der Fahrzeitberechnung ist.

**Comment by C1710** [comment]
> Um dem Problem mit den Höchstgeschwindigkeiten gerecht zu werden, gibt es den Twisting-Factor, der Teil der Fahrzeitberechnung ist.

Also grobe Höchstgeschwindigkeiten ließen sich auch aus den DB-Daten extrahieren (was ich für die Bestimmung einer SFS auch mache).
Da hast du dann sowas wie "ab 50 bis 120 km/h", obwohl die Strecke lt. ORM nur bis 110 km/h erlaubt.

Wenn so grobe Höchstgeschwindigkeiten auch okay sind, kann ich die eben integrieren 🤷‍♀️

**Comment by marhei** [comment]
50 oder 100 km/h macht schon einen gewissen Unterschied. Ich habe die Geschwindigkeit bisher aus dem entsprechenden Layer der Openrailwaysmap entnommen.

**Comment by C1710** [comment]
> 50 oder 100 km/h macht schon einen gewissen Unterschied. Ich habe die Geschwindigkeit bisher aus dem entsprechenden Layer der Openrailwaysmap entnommen.

Da weiß ich halt nicht, ob/wie das automatisiert geht :D

**Comment by bjoernma** [comment]
Die Openrailwaymap hat dafür selbst noch keine API. Aber da es OSM-Daten sind, geht das halt per overpass (s. Query oben). Das ist dann aber halt auf Basis der Länge jedes einzelnen Streckenstückchens, was kurz sein kann, aber nicht muss, man wird also einiges an merging (um beide Gleise zu synchronisieren, aber auch die kleinen Stückchen in isogeschwindigkeiten zu transferieren) betreiben müssen.

**Comment by f2k1de** [comment]
Würde ja schon reichen wenn man automatisch die Koordinaten übernehmen kann aus OSM oder DB CSVs

**Comment by bjoernma** [comment]
Koordinaten sind kein Problem, müsste aber geklärt sein, dass das dann im ersten Schritt keine int sind, sondern irgendwas floatiges.

**Comment by f2k1de** [comment]
Hab mir mal was gebaut: https://tcroute.f2k1.de/
