### ISSUE TITLE
Fehlerhafte Platzierung von Bahnhöfe in Richtung Berlin

### ISSUE THREAD

**Issue by marhei** [marhei/TrainCompany-Data#92]
<img width="511" alt="Capture d’écran 2022-06-26 à 13 12 47" src="https://user-images.githubusercontent.com/10304183/175811448-88c40b34-2bad-4261-bb13-b32b874cb502.png">

**Comment by C1710** [comment]
Also die Bahnhöfe sind nicht fehlerhaft platziert, nur gehe ich mal davon aus, dass die Strecken die falschen Bahnhöfe verbinden...

**Comment by C1710** [comment]
#94

**Comment by marhei** [comment]
Okay, tut mir leid, das habe ich nicht beachtet. Kenne mich in der Ecke da oben nicht so gut aus.
