### ISSUE TITLE
Kreuzende Strecken, aber Kreuzungsbahnhof fehlt!

### ISSUE THREAD

**Issue by marhei** [marhei/TrainCompany-Data#93]
Wieso ist Bruchsal als Knotenbahnhof definiert?

Wieso gibt es die Strecke Bruchsal - Gemersheim und die Strecke Hockenheim-Karlsruhe aber nicht Graben Neudorf?

<img width="178" alt="Capture d’écran 2022-06-26 à 13 19 30" src="https://user-images.githubusercontent.com/10304183/175811623-40f0cd7d-df2b-4543-8acf-ef4ed97cc1f9.png">

@drive-n-code

**Comment by marhei** [comment]
Zusätzlich folgende Probleme:

- Strecke RM-RN war doppelt
- Streckennamen zufällig gewählt
- Quasi keine Unterwegsbahnhöfe
- Strecke Bruchsal Gemersheim doppelt

**Comment by drive-n-code** [comment]
Darf du gerne mir assignen, dann kümmere ich mich nochmal um Nachlieferung.

**Comment by marhei** [comment]
Problem ist jetzt behobe
<img width="303" alt="Capture d’écran 2022-06-26 à 14 23 56" src="https://user-images.githubusercontent.com/10304183/175813956-4f7fec95-0c56-4502-954a-9d6793ccfa82.png">
n
